//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModiIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Modi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_Modi()
        {
            this.RC_modi = new HashSet<RC_modi>();
        }
    
        public int RCustomerNum { get; set; }
        public string RCode { get; set; }
        public string RWeddingDate { get; set; }
        public string RDate { get; set; }
        public string RDateHour { get; set; }
        public string RCustomerName { get; set; }
        public string RCustomerSurname { get; set; }
        public string RCustomerPhone { get; set; }
        public string RCustomerCity { get; set; }
        public string RSuccess { get; set; }
        public string RCancelled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RC_modi> RC_modi { get; set; }
    }
}
