//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModiIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_modi
    {
        public int RChoiceId { get; set; }
        public string RCode { get; set; }
        public string RCNyfiko { get; set; }
        public string RBrandName { get; set; }
        public string RCNyfikoDesc { get; set; }
    
        public virtual R_Modi R_Modi { get; set; }
    }
}
